language: node_js
arch:
 - amd64
 - ppc64le
git:
  depth: 5
cache: yarn
branches:
  only:
    - master
    - v7
matrix:
  include:
    - node_js: '10'
      after_success: 'bash <(curl -s https://codecov.io/bash)'
    - node_js: '12'
    - node_js: '14'
install:
  - yarn install --frozen-lockfile
script:
  - yarn run check:all
